In [47]:
!pip install mlflow


In [5]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import os # navigate through defferent files
import numpy as np
import wandb
import mlflow
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Bidirectional, Dense, Dropout
from tensorflow.keras.metrics import Precision, Recall, AUC
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.backend import epsilon

Loading data

In [6]:
import wandb
import mlflow
import tensorflow as tf

# Initialize Weights & Biases (W&B)
wandb.login()
wandb.init(project="toxicity-detection")

wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: e20189 (e20189-university-of-peradeniya) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin


In [7]:
df = pd.read_csv('/content/drive/MyDrive/CommentToxicity/jigsaw-toxic-comment-classification-challenge/train.csv/train.csv') # train data set

In [8]:
df[df['toxic'] ==1].head()

id                                       comment_text  \
6   0002bcb3da6cb337       COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK   
12  0005c987bdfc9d4b  Hey... what is it..\r\n@ | talk .\r\nWhat is i...   
16  0007e25b2121310b  Bye! \r\n\r\nDon't look, come or think of comm...   
42  001810bf8c45bf5f  You are gay or antisemmitian? \r\n\r\nArchange...   
43  00190820581d90ce           FUCK YOUR FILTHY MOTHER IN THE ASS, DRY!   

    toxic  severe_toxic  obscene  threat  insult  identity_hate  
6       1             1        1       0       1              0  
12      1             0        0       0       0              0  
16      1             0        0       0       0              0  
42      1             0        1       0       1              1  
43      1             0        1       0       1              0

In [10]:
id = 12
df.iloc[id]['comment_text']


'Hey... what is it..\r\n@ | talk .\r\nWhat is it... an exclusive group of some WP TALIBANS...who are good at destroying, self-appointed purist who GANG UP any one who asks them questions abt their ANTI-SOCIAL and DESTRUCTIVE (non)-contribution at WP?\r\n\r\nAsk Sityush to clean up his behavior than issue me nonsensical warnings...'

In [11]:
df[df.columns[2:]].iloc[id]

toxic            1
severe_toxic     0
obscene          0
threat           0
insult           0
identity_hate    0
Name: 12, dtype: int64

Preprocessing

In [12]:
from tensorflow.keras.layers import TextVectorization

In [13]:
df.columns

Index(['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate'],
      dtype='object')

In [14]:
y = df[df.columns[2:]].values # converting the measuring values in the data frames to a matrix as labels

In [15]:
x = df['comment_text'] # take the comment text as inputs

In [16]:
MAX_WORDS = 200000 # Number of vocab in the dictionary
vectorizer = TextVectorization(max_tokens=MAX_WORDS , output_sequence_length=1800 ,output_mode='int') # cap the max length of inputs to 1800 words and the model outputs data in the integer format

In [17]:
vectorizer.adapt(x.values) # fit the vectorizer to the data , learn the words in the inputs

In [18]:
import tensorflow as tf
import pickle

# Save vectorizer weights
vectorizer_weights = vectorizer.get_weights()
with open("vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer_weights, f)


In [19]:
import pickle
from tensorflow.keras.layers import TextVectorization

#  Save the vocabulary
vocab = vectorizer.get_vocabulary()
with open("vectorizer_vocab.pkl", "wb") as f:
    pickle.dump(vocab, f)

print(" Vocabulary saved successfully!")


 Vocabulary saved successfully!


In [20]:
vectorizer.get_vocabulary()

['',
 '[UNK]',
 'the',
 'to',
 'of',
 'and',
 'a',
 'you',
 'i',
 'is',
 'that',
 'in',
 'it',
 'for',
 'this',
 'not',
 'on',
 'be',
 'as',
 'have',
 'are',
 'your',
 'with',
 'if',
 'article',
 'was',
 'or',
 'but',
 'page',
 'my',
 'an',
 'from',
 'by',
 'do',
 'at',
 'about',
 'me',
 'so',
 'wikipedia',
 'can',
 'what',
 'there',
 'all',
 'has',
 'will',
 'talk',
 'please',
 'would',
 'its',
 'no',
 'one',
 'just',
 'like',
 'they',
 'he',
 'dont',
 'which',
 'any',
 'been',
 'should',
 'more',
 'we',
 'some',
 'other',
 'who',
 'see',
 'here',
 'also',
 'his',
 'think',
 'im',
 'because',
 'know',
 'how',
 'am',
 'people',
 'why',
 'edit',
 'articles',
 'only',
 'out',
 'up',
 'when',
 'were',
 'use',
 'then',
 'may',
 'time',
 'did',
 'them',
 'now',
 'being',
 'their',
 'than',
 'thanks',
 'even',
 'get',
 'make',
 'good',
 'had',
 'very',
 'information',
 'does',
 'could',
 'well',
 'want',
 'such',
 'sources',
 'way',
 'name',
 'these',
 'deletion',
 'pages',
 'first',
 'help'

In [21]:
# example of text tokenizing
vectorizer("Helloo everyone whassup my homies")[:5]

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([    1,   523,     1,    29, 37427])>

In [22]:
# tokenizing the dataset
vectorizedText = vectorizer(x.values)

In [23]:
vectorizedText

<tf.Tensor: shape=(159571, 1800), dtype=int64, numpy=
array([[  645,    76,     2, ...,     0,     0,     0],
       [    1,    54,  2489, ...,     0,     0,     0],
       [  425,   441,    70, ...,     0,     0,     0],
       ...,
       [32445,  7392,   383, ...,     0,     0,     0],
       [    5,    12,   534, ...,     0,     0,     0],
       [    5,     8,   130, ...,     0,     0,     0]])>

In [24]:
tf.data.Dataset.list_files

<function tensorflow.python.data.ops.dataset_ops.DatasetV2.list_files(file_pattern, shuffle=None, seed=None, name=None) -> 'DatasetV2'>

In [25]:
#MCSHBAP - map , cache ,shuffle ,batch ,prefetch from tenserflow slices
# batch the data
dataset = tf.data.Dataset.from_tensor_slices((vectorizedText,y))# passing the input data and the corresponding labels
dataset = dataset.cache()
dataset = dataset.shuffle(160000)
dataset = dataset.batch(16)
dataset = dataset.prefetch(8)# helps prevent bottlenecks
#Prefetching enables the system to load the next batch of data while the current batch is being processed by the GPU.


In [26]:
dataset.as_numpy_iterator().next()
# load a batch

(array([[ 2815,   218,   168, ...,     0,     0,     0],
        [13904,   774,    11, ...,     0,     0,     0],
        [ 2923, 51659,     2, ...,     0,     0,     0],
        ...,
        [  637,    51,    96, ...,     0,     0,     0],
        [   63,   430,     8, ...,     0,     0,     0],
        [    2,   115,   396, ...,     0,     0,     0]]),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]))

In [27]:
batch_x , batch_y = dataset.as_numpy_iterator().next()

In [28]:
batch_x.shape # inputs
batch_y.shape

(16, 6)

In [29]:
train = dataset.take(int(len(dataset )*0.7))
val = dataset.skip(int(len(dataset)*0.7)).take(int(len(dataset)*0.2))
test = dataset.skip(int(len(dataset)*0.9)).take(int(len(dataset)*0.1))

In [30]:
train_generator = train.as_numpy_iterator()

In [31]:
train_generator.next()

(array([[  561,  8263,  5672, ...,     0,     0,     0],
        [   11, 14172,     4, ...,     0,     0,     0],
        [  490,     8,   221, ...,     0,     0,     0],
        ...,
        [    8,    39,   151, ...,     0,     0,     0],
        [ 5705,     8,   597, ...,     0,     0,     0],
        [  288,     2,   121, ...,     0,     0,     0]]),
 array([[1, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 1, 1, 0, 1, 0],
        [1, 0, 1, 0, 1, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]))

create sequencial model

In [32]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM , Dropout, Bidirectional,Dense ,Embedding

In [33]:
model  = Sequential()# instantiate the sequential API so after that we can add the layers to the model?
# create the embedding layer

model.add(Embedding(MAX_WORDS+1,32)) # +1 is for the unknown words
# bidirectional LSTM layer
model.add(Bidirectional(LSTM(64 , activation = "tanh")))
# dense layers
model.add(Dense(128,activation = "relu"))
model.add(Dense(256, activation = "relu"))
model.add(Dense(138, activation = "relu"))
model.add(Dropout(0.3))  # Drop 30% of neurons randomly. Dropout Layer (Before Final Output)

# converting the previous dense layer output to values between 0 and 1
model.add(Dense(6 , activation = "sigmoid"))
# dense layers connect each input to each output within its layer

In [34]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ bidirectional (Bidirectional)        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ ?                           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Compile the model with F1 score , accuracy, recall ,precision Metrics

In [35]:
class F1Score(tf.keras.metrics.Metric):
    def __init__(self, name="f1_score", **kwargs):
        super(F1Score, self).__init__(name=name, **kwargs)
        self.precision = Precision()
        self.recall = Recall()

    def update_state(self, y_true, y_pred, sample_weight=None):
        self.precision.update_state(y_true, y_pred, sample_weight)
        self.recall.update_state(y_true, y_pred, sample_weight)

    def result(self):
        precision = self.precision.result()
        recall = self.recall.result()
        return 2 * (precision * recall) / (precision + recall + epsilon())

    def reset_states(self):
        self.precision.reset_states()
        self.recall.reset_states()

In [36]:
import tensorflow as tf
from tensorflow.keras.metrics import Precision, Recall, AUC
from tensorflow.keras.backend import epsilon


model.compile(
    loss="binary_crossentropy",
    optimizer="adam",
    metrics=[
        "accuracy",
        Precision(name="precision"),
        Recall(name="recall"),
        AUC(name="auc"),
        F1Score()
    ]
)

MLOPs integrated training and validation

In [ ]:
# MLflow Experiment Setup
mlflow.set_experiment("toxicity_detection")

with mlflow.start_run():
    # Train Model with Logging
    history = model.fit(
        train,
        epochs=20,
        validation_data=val,
        callbacks=[
            EarlyStopping(monitor="val_loss", patience=3),
            WandbMetricsLogger(),  # Logs to W&B
            WandbModelCheckpoint(filepath="wandb_model.keras", save_best_only=True)  # ✅ Saves best model
        ]
    )

    # Retrieve Final Metrics
    final_accuracy = history.history["accuracy"][-1]
    final_loss = history.history["loss"][-1]

    # Log Metrics to MLflow
    mlflow.log_param("epochs", 20)
    mlflow.log_metric("accuracy", final_accuracy)
    mlflow.log_metric("loss", final_loss)

    # Save and Log Model
    model.save("toxicity_model.h5")
    mlflow.log_artifact("toxicity_model.h5")

    # Log Epoch-wise Metrics
    for epoch in range(len(history.history["loss"])):
        mlflow.log_metric("train_loss", history.history["loss"][epoch], step=epoch)
        mlflow.log_metric("val_loss", history.history["val_loss"][epoch], step=epoch)
        mlflow.log_metric("train_f1", history.history["f1_score"][epoch], step=epoch)
        mlflow.log_metric("val_f1", history.history["val_f1_score"][epoch], step=epoch)
        mlflow.log_metric("train_accuracy", history.history["accuracy"][epoch], step=epoch)
        mlflow.log_metric("val_accuracy", history.history["val_accuracy"][epoch], step=epoch)

    # Log Metrics to W&B
    wandb.log({
        "accuracy": final_accuracy,
        "loss": final_loss
    })

    # Plot Loss & F1-Score Curves
    def plot_and_log_metric(metric_name, title):
        plt.figure(figsize=(8, 5))
        plt.plot(history.history[metric_name], label="Train " + metric_name.capitalize())
        plt.plot(history.history["val_" + metric_name], label="Validation " + metric_name.capitalize())
        plt.xlabel("Epochs")
        plt.ylabel(metric_name.capitalize())
        plt.legend()
        plt.title(title)
        plt.savefig(f"{metric_name}_plot.png")
        mlflow.log_artifact(f"{metric_name}_plot.png")  # Log to MLflow
        wandb.log({f"{metric_name}_plot": wandb.Image(f"{metric_name}_plot.png")})  # Log to W&B
        plt.close()

    # Log Loss & F1-score Plots
    plot_and_log_metric("loss", "Loss over Epochs")
    plot_and_log_metric("f1_score", "F1 Score over Epochs")

    print(f"MLflow & W&B logging complete with accuracy: {final_accuracy:.2f}")

# Finish W&B Run
wandb.finish()

Epoch 1/20
6981/6981 ━━━━━━━━━━━━━━━━━━━━ 733s 105ms/step - accuracy: 0.9910 - auc: 0.9849 - f1_score: 0.7567 - loss: 0.0447 - precision: 0.8301 - recall: 0.6953 - val_accuracy: 0.9937 - val_auc: 0.9913 - val_f1_score: 0.7823 - val_loss: 0.0396 - val_precision: 0.8483 - val_recall: 0.7259
Epoch 2/20
6981/6981 ━━━━━━━━━━━━━━━━━━━━ 733s 105ms/step - accuracy: 0.9916 - auc: 0.9882 - f1_score: 0.7786 - loss: 0.0388 - precision: 0.8391 - recall: 0.7263 - val_accuracy: 0.9892 - val_auc: 0.9908 - val_f1_score: 0.8000 - val_loss: 0.0350 - val_precision: 0.8684 - val_recall: 0.7415
Epoch 3/20
6981/6981 ━━━━━━━━━━━━━━━━━━━━ 733s 105ms/step - accuracy: 0.9933 - auc: 0.9912 - f1_score: 0.8024 - loss: 0.0349 - precision: 0.8509 - recall: 0.7592 - val_accuracy: 0.9946 - val_auc: 0.9935 - val_f1_score: 0.8105 - val_loss: 0.0310 - val_precision: 0.9038 - val_recall: 0.7347
Epoch 4/20
6981/6981 ━━━━━━━━━━━━━━━━━━━━ 733s 105ms/step - accuracy: 0.9909 - auc: 0.9922 - f1_score: 0.8205 - loss: 0.0326 - pre

MLflow & W&B logging complete with accuracy: 0.93


In [40]:
import wandb
import matplotlib.pyplot as plt
import mlflow

# Initialize W&B Run (Load previous run)
api = wandb.Api()
run = api.run("toxicity-detection/i2zqmk3c")
history = run.history()
print(history.columns)  # Shows all available metric names
mlflow.set_tracking_uri("http://127.0.0.1:5000")  #

# Convert W&B history to match your format
history_dict = {
    "loss": history["epoch/loss"].tolist(),
    "val_loss": history["epoch/val_loss"].tolist(),
    "f1_score": history["epoch/f1_score"].tolist(),
    "val_f1_score": history["epoch/val_f1_score"].tolist(),
    "accuracy": history["epoch/accuracy"].tolist(),
    "val_accuracy": history["epoch/val_accuracy"].tolist(),
    "precision": history["epoch/precision"].tolist(),
    "val_precision": history["epoch/val_precision"].tolist(),
    "recall": history["epoch/recall"].tolist(),
    "val_recall": history["epoch/val_recall"].tolist(),
    "auc": history["epoch/auc"].tolist(),
    "val_auc": history["epoch/val_auc"].tolist(),
    "learning_rate": history["epoch/learning_rate"].tolist(),  # No val version
}

# Define function to re-plot and log (handling missing val_ cases)
def plot_and_log_metric(metric_name, title, has_val=True):
    plt.figure(figsize=(8, 5))
    plt.plot(history_dict[metric_name], label="Train " + metric_name.capitalize())

    # Only plot validation if it exists
    if has_val:
        plt.plot(history_dict["val_" + metric_name], label="Validation " + metric_name.capitalize())

    plt.xlabel("Epochs")
    plt.ylabel(metric_name.capitalize())
    plt.legend()
    plt.title(title)
    plt.savefig(f"{metric_name}_plot.png")
    mlflow.log_artifact(f"{metric_name}_plot.png")  # Log to MLflow
    wandb.log({f"{metric_name}_plot": wandb.Image(f"{metric_name}_plot.png")})  # Log to W&B
    plt.close()

# Recreate and log all plots
plot_and_log_metric("loss", "Loss over Epochs")
plot_and_log_metric("f1_score", "F1 Score over Epochs")
plot_and_log_metric("accuracy", "Accuracy over Epochs")
plot_and_log_metric("precision", "Precision over Epochs")
plot_and_log_metric("recall", "Recall over Epochs")
plot_and_log_metric("auc", "AUC over Epochs")
plot_and_log_metric("learning_rate", "Learning Rate over Epochs", has_val=False)  # No validation version

print("Plots regenerated and logged successfully.")


Index(['loss', '_runtime', 'epoch/val_precision', 'epoch/accuracy',
       'epoch/f1_score', 'epoch/val_recall', 'accuracy', 'epoch/auc',
       'epoch/learning_rate', '_step', 'epoch/precision', 'epoch/loss',
       'epoch/recall', 'epoch/val_auc', 'loss_plot', 'epoch/val_f1_score',
       '_timestamp', 'epoch/val_accuracy', 'epoch/epoch', 'f1_score_plot',
       'epoch/val_loss'],
      dtype='object')
Plots regenerated and logged successfully.


In [41]:
import mlflow
from tensorflow.keras.models import load_model  # Correct way to load a Keras model

# Load the pre-trained model
model = load_model("/content/toxicity_model.h5")
mlflow.set_tracking_uri("http://127.0.0.1:5000")  # Or your actual MLflow server URL

# End any active MLflow run if it exists
mlflow.end_run()

# If experiment does not exist, create one
experiment_name = "toxicity_detection"
try:
    experiment = mlflow.create_experiment(experiment_name)
except:
    # If experiment already exists, just get it
    experiment = mlflow.get_experiment_by_name(experiment_name)

# Start a new run within the experiment
with mlflow.start_run(experiment_id=experiment.experiment_id):
    # Log the model
    mlflow.keras.log_model(model, "model")

    # Assuming you have history_dict available (from your training history)
    # Log metrics to MLflow (no retraining required)
    for epoch in range(len(history_dict["loss"])):
        mlflow.log_metric("loss", history_dict["loss"][epoch], step=epoch)
        mlflow.log_metric("val_loss", history_dict["val_loss"][epoch], step=epoch)
        mlflow.log_metric("accuracy", history_dict["accuracy"][epoch], step=epoch)
        mlflow.log_metric("val_accuracy", history_dict["val_accuracy"][epoch], step=epoch)
        mlflow.log_metric("f1_score", history_dict["f1_score"][epoch], step=epoch)
        mlflow.log_metric("val_f1_score", history_dict["val_f1_score"][epoch], step=epoch)
        mlflow.log_metric("precision", history_dict["precision"][epoch], step=epoch)
        mlflow.log_metric("val_precision", history_dict["val_precision"][epoch], step=epoch)
        mlflow.log_metric("recall", history_dict["recall"][epoch], step=epoch)
        mlflow.log_metric("val_recall", history_dict["val_recall"][epoch], step=epoch)
        mlflow.log_metric("auc", history_dict["auc"][epoch], step=epoch)
        mlflow.log_metric("val_auc", history_dict["val_auc"][epoch], step=epoch)

    # Log the plots that were saved during training
    for metric_name in ["loss", "f1_score", "accuracy", "precision", "recall", "auc"]:
        mlflow.log_artifact(f"{metric_name}_plot.png")

print("Model and metrics have been logged successfully.")
import mlflow
import mlflow.keras

# Get experiment by name (or ID)
experiment = mlflow.get_experiment_by_name("toxicity_detection")

# Retrieve all runs
runs = mlflow.search_runs(experiment_ids=[experiment.experiment_id])
print(runs.columns)

# Print the metrics for each run (e.g., accuracy, loss)
print(runs[["run_id", "metrics.accuracy", "metrics.loss"]])


2025/03/06 08:20:45 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.


🏃 View run gaudy-cub-796 at: http://127.0.0.1:5000/#/experiments/0/runs/3748e07fa1374f3cada78f70bd771cfa
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/0


2025/03/06 08:20:55 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.


🏃 View run fortunate-loon-507 at: http://127.0.0.1:5000/#/experiments/841964652538824668/runs/9f04ad5c2ba943ba8d94d3630db19bb0
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/841964652538824668
Model and metrics have been logged successfully.
Index(['run_id', 'experiment_id', 'status', 'artifact_uri', 'start_time',
       'end_time', 'metrics.val_accuracy', 'metrics.val_recall',
       'metrics.val_auc', 'metrics.recall', 'metrics.loss',
       'metrics.precision', 'metrics.val_precision', 'metrics.val_loss',
       'metrics.accuracy', 'metrics.val_f1_score', 'metrics.auc',
       'metrics.f1_score', 'tags.mlflow.log-model.history',
       'tags.mlflow.source.type', 'tags.mlflow.user', 'tags.mlflow.runName',
       'tags.mlflow.source.name'],
      dtype='object')
                             run_id  metrics.accuracy  metrics.loss
0  9f04ad5c2ba943ba8d94d3630db19bb0               NaN           NaN


In [ ]:
import mlflow
import mlflow.keras

# Get experiment by name (or ID)
experiment = mlflow.get_experiment_by_name("toxicity_detection")

# Retrieve all runs
runs = mlflow.search_runs(experiment_ids=[experiment.experiment_id])
print(runs.columns)

# Print the metrics for each run (e.g., accuracy, loss)
print(runs[["run_id", "metrics.accuracy", "metrics.loss"]])


Index(['run_id', 'experiment_id', 'status', 'artifact_uri', 'start_time',
       'end_time', 'metrics.loss', 'metrics.auc', 'metrics.val_auc',
       'metrics.val_recall', 'metrics.accuracy', 'metrics.f1_score',
       'metrics.val_accuracy', 'metrics.val_loss', 'metrics.precision',
       'metrics.val_f1_score', 'metrics.val_precision', 'metrics.recall',
       'tags.mlflow.source.name', 'tags.mlflow.source.type',
       'tags.mlflow.runName', 'tags.mlflow.log-model.history',
       'tags.mlflow.user'],
      dtype='object')
                             run_id  metrics.accuracy  metrics.loss
0  a49a4770dcc14ec8b5f24786add8d9f0               NaN           NaN
1  86ac75d6a3f44eff836c0aee3efe2804               NaN           NaN


In [ ]:
from pyngrok import ngrok
!mlflow ui --port 5000 &
public_url = ngrok.connect(port="5000")
print(f"MLflow Tracking UI: {public_url}")

In [81]:
from tensorflow.keras.layers import LSTM, Bidirectional

custom_objects = {"LSTM": LSTM, "Bidirectional": Bidirectional}

model = tf.keras.models.load_model('/content/toxicity_model.h5', custom_objects=custom_objects)


Make Predictions

In [82]:
input_str = vectorizer("Heyy I hate you")
res = model.predict(np.expand_dims(input_str, axis = 0))
# printout the columns
print(df.columns[2:])
print(res)

input_str = vectorizer("You looks very nice")
res = model.predict(np.expand_dims(input_str, axis = 0))
# printout the columns
print(df.columns[2:])
print(res)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 310ms/step
Index(['toxic', 'severe_toxic', 'obscene', 'threat', 'insult',
       'identity_hate'],
      dtype='object')
[[0.6889598  0.00483085 0.07420572 0.0524078  0.14637259 0.10724357]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
Index(['toxic', 'severe_toxic', 'obscene', 'threat', 'insult',
       'identity_hate'],
      dtype='object')
[[5.3074697e-11 0.0000000e+00 2.5806218e-19 8.3492614e-38 8.7714351e-24
  1.4263595e-30]]


Evaluate Model on Test dataset

In [83]:
batch_X, batch_y = test.as_numpy_iterator().next()
(model.predict(batch_X) > 0.5).astype(int)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 414ms/step


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [80]:
res.shape

(1, 6)

In [ ]:
# Evaluate Model on Test Data
test_results = model.evaluate(test, verbose=1)

# Extract Metrics
test_loss = test_results[0]
test_accuracy = test_results[1]
test_precision = test_results[2]
test_recall = test_results[3]
test_auc = test_results[4]
test_f1 = 2 * (test_precision * test_recall) / (test_precision + test_recall + tf.keras.backend.epsilon())

print(f"Test Accuracy: {test_accuracy:.4f}")
print(f"Test F1-Score: {test_f1:.4f}")
print(f"Test recall: {test_recall:.4f}")
print(f"Test Precision: {test_precision:.4f}")
print(f"Test loss: {test_loss:.4f}")


997/997 ━━━━━━━━━━━━━━━━━━━━ 180s 178ms/step - accuracy: 0.9877 - auc: 0.9975 - f1_score: 0.2112 - loss: 0.0091 - precision: 0.9523 - recall: 0.9477
Test Accuracy: 0.9866
Test F1-Score: 0.9498
Test recall: 0.9498
Test Precision: 0.9498
Test loss: 0.0095


In [ ]:
# Ensure W&B is initialized before logging
wandb.init(project="toxicity-detection", name="test_evaluation")

# Log Test Metrics to W&B
wandb.log({
    "test_loss": test_loss,
    "test_accuracy": test_accuracy,
    "test_precision": test_precision,
    "test_recall": test_recall,
    "test_f1_score": test_f1,
    "test_auc": test_auc
})

# Finish the W&B run
wandb.finish()


In [84]:
!pip install fastapi uvicorn pyngrok

In [85]:
from fastapi import FastAPI
from pydantic import BaseModel
import tensorflow as tf
import numpy as np

app =FastAPI()

model =tf.keras.models.load_model("/content/toxicity_model.h5")
class InputText(BaseModel):
  text:str
@app.post("/predict")
async def predict(input_text : InputText):
  text: input_text.text
  vect_text = vectorizer(text)
  prediction = model.predict([text])
  return {"prediction": prediction.tolist()}

In [3]:
# Step 1: Install dependencies if not installed
!pip install fastapi uvicorn pyngrok mlflow tensorflow

# Step 2: Run FastAPI in the background
!nohup uvicorn server:app --host 0.0.0.0 --port 8000 --reload &

# Step 3: Start ngrok for FastAPI
from pyngrok import ngrok
ngrok.set_auth_token("2tVdIx30fQWA14bNtDn4lfBR9tE_77bGYGjjdXZRXD17uKHy5")  # Replace with your token
public_url = ngrok.connect(8000)
print(f"FastAPI is running at {public_url}")

# Step 4: Start MLflow UI
!nohup mlflow ui --port 5000 &

# Step 5: Expose MLflow UI with ngrok
mlflow_url = ngrok.connect(5000)
print(f"MLflow UI is available at {mlflow_url}")


nohup: appending output to 'nohup.out'
FastAPI is running at NgrokTunnel: "https://9b99-34-59-186-82.ngrok-free.app" -> "http://localhost:8000"
nohup: appending output to 'nohup.out'
MLflow UI is available at NgrokTunnel: "https://297c-34-59-186-82.ngrok-free.app" -> "http://localhost:5000"


In [39]:
import wandb
import matplotlib.pyplot as plt
import mlflow

# Initialize W&B Run (Load previous run)
api = wandb.Api()
run = api.run("toxicity-detection/i2zqmk3c")
history = run.history()
print(history.columns)  # Shows all available metric names
mlflow.set_tracking_uri("http://127.0.0.1:5000")  # Or your actual MLflow server URL


# Convert W&B history to match your format
history_dict = {
    "loss": history["epoch/loss"].tolist(),
    "val_loss": history["epoch/val_loss"].tolist(),
    "f1_score": history["epoch/f1_score"].tolist(),
    "val_f1_score": history["epoch/val_f1_score"].tolist(),
    "accuracy": history["epoch/accuracy"].tolist(),
    "val_accuracy": history["epoch/val_accuracy"].tolist(),
    "precision": history["epoch/precision"].tolist(),
    "val_precision": history["epoch/val_precision"].tolist(),
    "recall": history["epoch/recall"].tolist(),
    "val_recall": history["epoch/val_recall"].tolist(),
    "auc": history["epoch/auc"].tolist(),
    "val_auc": history["epoch/val_auc"].tolist(),
    "learning_rate": history["epoch/learning_rate"].tolist(),  # No val version
}

# Define function to re-plot and log (handling missing val_ cases)
def plot_and_log_metric(metric_name, title, has_val=True):
    plt.figure(figsize=(8, 5))
    plt.plot(history_dict[metric_name], label="Train " + metric_name.capitalize())

    # Only plot validation if it exists
    if has_val:
        plt.plot(history_dict["val_" + metric_name], label="Validation " + metric_name.capitalize())

    plt.xlabel("Epochs")
    plt.ylabel(metric_name.capitalize())
    plt.legend()
    plt.title(title)
    plt.savefig(f"{metric_name}_plot.png")
    mlflow.log_artifact(f"{metric_name}_plot.png")  # Log to MLflow
    wandb.log({f"{metric_name}_plot": wandb.Image(f"{metric_name}_plot.png")})  # Log to W&B
    plt.close()

# Recreate and log all plots
plot_and_log_metric("loss", "Loss over Epochs")
plot_and_log_metric("f1_score", "F1 Score over Epochs")
plot_and_log_metric("accuracy", "Accuracy over Epochs")
plot_and_log_metric("precision", "Precision over Epochs")
plot_and_log_metric("recall", "Recall over Epochs")
plot_and_log_metric("auc", "AUC over Epochs")
plot_and_log_metric("learning_rate", "Learning Rate over Epochs", has_val=False)  # No validation version

print("Plots regenerated and logged successfully.")


Index(['loss', '_runtime', 'epoch/val_precision', 'epoch/accuracy',
       'epoch/f1_score', 'epoch/val_recall', 'accuracy', 'epoch/auc',
       'epoch/learning_rate', '_step', 'epoch/precision', 'epoch/loss',
       'epoch/recall', 'epoch/val_auc', 'loss_plot', 'epoch/val_f1_score',
       '_timestamp', 'epoch/val_accuracy', 'epoch/epoch', 'f1_score_plot',
       'epoch/val_loss'],
      dtype='object')
Plots regenerated and logged successfully.


In [87]:
from pyngrok import ngrok
!ngrok authtoken 2tVdIx30fQWA14bNtDn4lfBR9tE_77bGYGjjdXZRXD17uKHy5

!uvicorn --host 0.0.0.0 --port 8000 --reload app:app

public_url = ngrok.connect(8000)
print("FastAPI app is accessible at:", public_url)

Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml


INFO:     Will watch for changes in these directories: ['/content']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [22521] using StatReload
ERROR:    Error loading ASGI app. Could not import module "app".
INFO:     Stopping reloader process [22521]
FastAPI app is accessible at: NgrokTunnel: "https://a3b5-34-59-186-82.ngrok-free.app" -> "http://localhost:8000"


In [ ]:
with mlflow.start_run():
    # Log Test Metrics
    mlflow.log_metric("test_loss", test_loss)
    mlflow.log_metric("test_accuracy", test_accuracy)
    mlflow.log_metric("test_precision", test_precision)
    mlflow.log_metric("test_recall", test_recall)
    mlflow.log_metric("test_auc", test_auc)
    mlflow.log_metric("test_f1_score", test_f1)

    print(" Test results logged in MLflow")


 Test results logged in MLflow


Test using Gradio UI and Mflow integration

In [42]:
!pip install fastapi uvicorn pyngrok mlflow tensorflow gradio websockets


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 MB 37.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.1/322.1 kB 23.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.2/11.2 MB 98.5 MB/s eta 0:00:00
  Attempting uninstall: markupsafe
    Found existing installation: MarkupSafe 3.0.2
    Uninstalling MarkupSafe-3.0.2:
      Successfully uninstalled MarkupSafe-3.0.2


In [43]:
from fastapi import FastAPI, WebSocket
import tensorflow as tf
import numpy as np
import json
import pickle
import os
import mlflow

# Load the trained model
model = tf.keras.models.load_model("toxicity_model.h5")

# Load vectorizer
MAX_WORDS = 200000
vectorizer = tf.keras.layers.TextVectorization(max_tokens=MAX_WORDS, output_sequence_length=1800, output_mode='int')

if os.path.exists("vectorizer_vocab.pkl"):
    with open("vectorizer_vocab.pkl", "rb") as f:
        vocab = pickle.load(f)
    vectorizer.set_vocabulary(vocab)

# Start FastAPI
app = FastAPI()

# MLflow Experiment Setup
mlflow.set_tracking_uri("http://localhost:5000")
mlflow.set_experiment("Toxicity Detection")

# Function to Predict Toxicity & Log to MLflow
def predict_toxicity(message):
    with mlflow.start_run():
        input_text = tf.expand_dims(message, axis=0)
        input_text = vectorizer(input_text)
        prediction = model.predict(input_text)[0]

        # Log inputs & predictions to MLflow
        mlflow.log_param("input_text", message)
        for label, score in zip(["Toxic", "Severe Toxic", "Obscene", "Threat", "Insult", "Identity Hate"], prediction):
            mlflow.log_metric(label, float(score))

        return {label: round(float(score), 2) for label, score in zip(["Toxic", "Severe Toxic", "Obscene", "Threat", "Insult", "Identity Hate"], prediction)}

@app.websocket("/chat")
async def chatroom(websocket: WebSocket):
    await websocket.accept()
    while True:
        data = await websocket.receive_text()
        message_data = json.loads(data)
        message = message_data["message"]

        # Predict toxicity & log to MLflow
        toxicity_scores = predict_toxicity(message)

        await websocket.send_json({"message": message, "toxicity_scores": toxicity_scores})


2025/03/06 09:15:56 INFO mlflow.tracking.fluent: Experiment with name 'Toxicity Detection' does not exist. Creating a new experiment.


In [44]:
!nohup uvicorn server:app --host 0.0.0.0 --port 8000 --reload &


nohup: appending output to 'nohup.out'


In [45]:
public_url = ngrok.connect(8000)
print(f"FastAPI is running at {public_url}")


FastAPI is running at NgrokTunnel: "https://7ef4-34-59-186-82.ngrok-free.app" -> "http://localhost:8000"


In [48]:
!pgrep -a ngrok
!killall ngrok


26140 /root/.config/ngrok/ngrok start --none --log=stdout


In [49]:
!nohup mlflow ui --port 5000 &
mlflow_url = ngrok.connect(5000)
print(f"MLflow UI is available at {mlflow_url}")


nohup: appending output to 'nohup.out'
MLflow UI is available at NgrokTunnel: "https://0d8e-34-59-186-82.ngrok-free.app" -> "http://localhost:5000"


In [51]:
import gradio as gr
import websockets
import asyncio
import json

WEBSOCKET_URL = "https://0d8e-34-59-186-82.ngrok-free.app/"  # Replace with your FastAPI ngrok URL

async def send_message(message, history, user):
    if not user.strip():
        return history + [{"role": "assistant", "content": "⚠️ Please enter a username before sending messages."}]

    async with websockets.connect(WEBSOCKET_URL) as websocket:
        user_message = {"user": user, "message": message}
        await websocket.send(json.dumps(user_message))
        response = await websocket.recv()
        response_data = json.loads(response)

        history.append({"role": "user", "content": f"👤 {user}: {message}"})
        history.append({"role": "assistant", "content": f"🤖 Assistant: {response_data['message']} (Toxicity: {response_data['toxicity_scores']})"})
        return history

with gr.Blocks() as demo:
    username_input = gr.Textbox(label="Enter Your Name", placeholder="Type your name here...")
    chat_interface = gr.Chatbot([], type="messages", label="Toxicity Detection Chatroom")
    msg_input = gr.Textbox(label="Type your message here:")
    send_btn = gr.Button("Send")

    send_btn.click(fn=send_message, inputs=[msg_input, chat_interface, username_input], outputs=chat_interface)

demo.launch()


Running Gradio in a Colab notebook requires sharing enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://cb97fca029e4b842a4.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
